### ISSUE TITLE
アセットからインポートしたパーティクルのサイズを変えたい！

### ISSUE THREAD

**Issue by moooe** [naichilab/unity-simple-ranking#5]
アイテムにパーティクルをつけようと思い、アセットストアからフリーのパーティクルをインポートしました。

そこで、サイズを変えようと思い、
StartSizeを変えたのですが変わりません。
また、調べたところ、ScallingModeをLocalかHieralchyに変えればTransformのScaleから変えられると書いていたので試したのですが変わりません。

このほかに何を試したらよいでしょうか。

**Comment by naichilab** [comment]
@moooe あれ、このライブラリとは関係ない質問でしょうか？
自分はパーティクルをそんなに使ってないので即答できないですね・・・

Unityに関連するコミュニティがいくつかあるのでそういった場所で質問してみてもらえないでしょうか？
* Twitterで聞いてみたり
* Facebookの[Unityユーザー助け合い所](https://www.facebook.com/groups/unityuserj)とか
* [こういうコミュニティ](http://pafu-of-duck.hatenablog.com/entry/2018/04/30/093027)とか
* [お住いの地域のコミュニティ探してみたり](http://lycoris102.hatenablog.com/entry/2018/04/30/204940)とか

色々ありますので、居心地の良い場所をぜひ見つけてください〜
